export const GET_ITEM_REVALIDATION_START = 'GET_ITEM_REVALIDATION_START'
export const GET_ITEM_REVALIDATION_SUCCESS = 'GET_ITEM_REVALIDATION_SUCCESS'
export const GET_ITEM_REVALIDATION_FAIL = 'GET_ITEM_REVALIDATION_FAIL'
