export const GET_NON_COMPLIANCE_START = 'GET_NON_COMPLIANCE_START'
export const GET_NON_COMPLIANCE_SUCCESS = 'GET_NON_COMPLIANCE_SUCCESS'
export const GET_NON_COMPLIANCE_FAIL = 'GET_NON_COMPLIANCE_FAIL'

export const GET_COMPLIANCE_DETAILS_START = 'GET_COMPLIANCE_DETAILS_START'
export const GET_COMPLIANCE_DETAILS_SUCCESS = 'GET_COMPLIANCE_DETAILS_SUCCESS'
export const GET_COMPLIANCE_DETAILS_FAIL = 'GET_COMPLIANCE_DETAILS_FAIL'

export const GET_MAIL_LOG_START = 'GET_MAIL_LOG_START'
export const GET_MAIL_LOG_SUCCESS = 'GET_MAIL_LOG_SUCCESS'
export const GET_MAIL_LOG_FAIL = 'GET_MAIL_LOG_FAIL'

export const SAVE_NON_COMPLIANCE_ADMIN_REMARK_START = 'SAVE_NON_COMPLIANCE_ADMIN_REMARK_START'
export const SAVE_NON_COMPLIANCE_ADMIN_REMARK_SUCCESS = 'SAVE_NON_COMPLIANCE_ADMIN_REMARK_SUCCESS'
export const SAVE_NON_COMPLIANCE_ADMIN_REMARK_FAIL = 'SAVE_NON_COMPLIANCE_ADMIN_REMARK_FAIL'

export const SAVE_OVER_SAMPLING_START = 'SAVE_OVER_SAMPLING_START'
export const SAVE_OVER_SAMPLING_SUCCESS = 'SAVE_OVER_SAMPLING_SUCCESS'
export const SAVE_OVER_SAMPLING_FAIL = 'SAVE_OVER_SAMPLING_FAIL'

export const OVER_SAMPLING_DETAILS_DATA_START = 'OVER_SAMPLING_DETAILS_DATA_START'
export const OVER_SAMPLING_DETAILS_DATA_SUCCESS = 'OVER_SAMPLING_DETAILS_DATA_SUCCESS'
export const OVER_SAMPLING_DETAILS_DATA_FAIL = 'OVER_SAMPLING_DETAILS_DATA_FAIL'
