
//BUISNESS_UNIT

export const GET_BUISNESS_UNIT_START = 'GET_BUISNESS_UNIT_START'
export const GET_BUISNESS_UNIT_SUCCESS = 'GET_BUISNESS_UNIT_SUCCESS'
export const GET_BUISNESS_UNIT_FAIL = 'GET_BUISNESS_UNIT_FAIL'

export const ADD_BUISNESS_UNIT_START = 'ADD_BUISNESS_UNIT_START'
export const ADD_BUISNESS_UNIT_SUCCESS = 'ADD_BUISNESS_UNIT_SUCCESS'
export const ADD_BUISNESS_UNIT_FAIL = 'ADD_BUISNESS_UNIT_FAIL'

export const EDIT_BUISNESS_UNIT_START = 'EDIT_BUISNESS_UNIT_START'
export const EDIT_BUISNESS_UNIT_SUCCESS = 'EDIT_BUISNESS_UNIT_SUCCESS'
export const EDIT_BUISNESS_UNIT_FAIL = 'EDIT_BUISNESS_UNIT_FAIL'

export const BUISNESS_UNIT_BY_ID_START = 'BUISNESS_UNIT_BY_ID_START'
export const BUISNESS_UNIT_BY_ID_SUCCESS = 'BUISNESS_UNIT_BY_ID_SUCCESS'
export const BUISNESS_UNIT_BY_ID_FAIL = 'BUISNESS_UNIT_BY_ID_FAIL'

//TEAM

export const GET_TEAM_START = 'GET_TEAM_START'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL'

export const ADD_TEAM_START = 'ADD_TEAM_START'
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS'
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL'

export const EDIT_TEAM_START = 'EDIT_TEAM_START'
export const EDIT_TEAM_SUCCESS = 'EDIT_TEAM_SUCCESS'
export const EDIT_TEAM_FAIL = 'EDIT_TEAM_FAIL'

export const TEAM_BY_ID_START = 'TEAM_BY_ID_START'
export const TEAM_BY_ID_SUCCESS = 'TEAM_BY_ID_SUCCESS'
export const TEAM_BY_ID_FAIL = 'TEAM_BY_ID_FAIL'


//USER
export const GET_USER_START = 'GET_USER_START'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const ADD_USER_START = 'ADD_USER_START'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'

export const EDIT_USER_START = 'EDIT_USER_START'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'

export const USER_BY_ID_START = 'USER_BY_ID_START'
export const USER_BY_ID_SUCCESS = 'USER_BY_ID_SUCCESS'
export const USER_BY_ID_FAIL = 'USER_BY_ID_FAIL'


//BRAND
export const GET_BRAND_START = 'GET_BRAND_START'
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS'
export const GET_BRAND_FAIL = 'GET_BRAND_FAIL'

export const ADD_BRAND_START = 'ADD_BRAND_START'
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS'
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL'

export const EDIT_BRAND_START = 'EDIT_BRAND_START'
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS'
export const EDIT_BRAND_FAIL = 'EDIT_BRAND_FAIL'

export const BRAND_BY_ID_START = 'BRAND_BY_ID_START'
export const BRAND_BY_ID_SUCCESS = 'BRAND_BY_ID_SUCCESS'
export const BRAND_BY_ID_FAIL = 'BRAND_BY_ID_FAIL'

//FF
export const GET_FF_START = 'GET_FF_START'
export const GET_FF_SUCCESS = 'GET_FF_SUCCESS'
export const GET_FF_FAIL = 'GET_FF_FAIL'

export const ADD_FF_START = 'ADD_FF_START'
export const ADD_FF_SUCCESS = 'ADD_FF_SUCCESS'
export const ADD_FF_FAIL = 'ADD_FF_FAIL'

export const EDIT_FF_START = 'EDIT_FF_START'
export const EDIT_FF_SUCCESS = 'EDIT_FF_SUCCESS'
export const EDIT_FF_FAIL = 'EDIT_FF_FAIL'

export const FF_BY_ID_START = 'FF_BY_ID_START'
export const FF_BY_ID_SUCCESS = 'FF_BY_ID_SUCCESS'
export const FF_BY_ID_FAIL = 'FF_BY_ID_FAIL'

export const FF_HISTORY_BY_ID_START = 'FF_HISTORY_BY_ID_START'
export const FF_HISTORY_BY_ID_SUCCESS = 'FF_HISTORY_BY_ID_SUCCESS'
export const FF_HISTORY_BY_ID_FAIL = 'FF_HISTORY_BY_ID_FAIL'


//VENDOR

export const GET_VENDOR_START = 'GET_VENDOR_START'
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS'
export const GET_VENDOR_FAIL = 'GET_VENDOR_FAIL'

export const ADD_VENDOR_START = 'ADD_VENDOR_START'
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS'
export const ADD_VENDOR_FAIL = 'ADD_VENDOR_FAIL'

export const EDIT_VENDOR_START = 'EDIT_VENDOR_START'
export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS'
export const EDIT_VENDOR_FAIL = 'EDIT_VENDOR_FAIL'

export const VENDOR_BY_ID_START = 'VENDOR_BY_ID_START'
export const VENDOR_BY_ID_SUCCESS = 'VENDOR_BY_ID_SUCCESS'
export const VENDOR_BY_ID_FAIL = 'VENDOR_BY_ID_FAIL'

export const GET_COST_CENTER_START = 'GET_COST_CENTER_START'
export const GET_COST_CENTER_SUCCESS = 'GET_COST_CENTER_SUCCESS'
export const GET_COST_CENTER_FAIL = 'GET_COST_CENTER_FAIL'

export const EDIT_COST_CENTER_START = 'EDIT_COST_CENTER_START'
export const EDIT_COST_CENTER_SUCCESS = 'EDIT_COST_CENTER_SUCCESS'
export const EDIT_COST_CENTER_FAIL = 'EDIT_COST_CENTER_FAIL'

export const GET_COST_CENTER_BY_ID_START = 'GET_COST_CENTER_BY_ID_START'
export const GET_COST_CENTER_BY_ID_SUCCESS = 'GET_COST_CENTER_BY_ID_SUCCESS'
export const GET_COST_CENTER_BY_ID_FAIL = 'GET_COST_CENTER_BY_ID_FAIL'

export const ADD_COST_CENTER_START = 'ADD_COST_CENTER_START'
export const ADD_COST_CENTER_SUCCESS = 'ADD_COST_CENTER_SUCCESS'
export const ADD_COST_CENTER_FAIL = 'ADD_COST_CENTER_FAIL'

export const GET_SAMPLES_START = 'GET_SAMPLES_START'
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS'
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL'

export const EDIT_SAMPLES_START = 'EDIT_SAMPLES_START'
export const EDIT_SAMPLES_SUCCESS = 'EDIT_SAMPLES_SUCCESS'
export const EDIT_SAMPLES_FAIL = 'EDIT_SAMPLES_FAIL'

export const GET_SAMPLES_BY_ID_START = 'GET_SAMPLES_BY_ID_START'
export const GET_SAMPLES_BY_ID_SUCCESS = 'GET_SAMPLES_BY_ID_SUCCESS'
export const GET_SAMPLES_BY_ID_FAIL = 'GET_SAMPLES_BY_ID_FAIL'

export const ADD_SAMPLES_START = 'ADD_SAMPLES_START'
export const ADD_SAMPLES_SUCCESS = 'ADD_SAMPLES_SUCCESS'
export const ADD_SAMPLES_FAIL = 'ADD_SAMPLES_FAIL'
