//VENDOR
export const GET_VENDOR_START = 'GET_VENDOR_START'
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS'
export const GET_VENDOR_FAIL = 'GET_VENDOR_FAIL'


export const ADD_VENDOR_START = 'ADD_VENDOR_START'
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS'
export const ADD_VENDOR_FAIL = 'ADD_VENDOR_FAIL'


export const EDIT_VENDOR_START = 'ADD_VENDOR_START'
export const EDIT_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS'
export const EDIT_VENDOR_FAIL = 'ADD_VENDOR_FAIL'

export const GET_VENDOR_BY_ID_START = 'GET_VENDOR_BY_ID_START'
export const GET_VENDOR_BY_ID_SUCCESS = 'GET_VENDOR_BY_ID_SUCCESS'
export const GET_VENDOR_BY_ID_FAIL = 'GET_VENDOR_BY_ID_FAIL'
