
//BUISNESS_UNIT

export const GET_BUISNESS_UNIT_START = 'GET_BUISNESS_UNIT_START'
export const GET_BUISNESS_UNIT_SUCCESS = 'GET_BUISNESS_UNIT_SUCCESS'
export const GET_BUISNESS_UNIT_FAIL = 'GET_BUISNESS_UNIT_FAIL'

export const ADD_BUISNESS_UNIT_START = 'ADD_BUISNESS_UNIT_START'
export const ADD_BUISNESS_UNIT_SUCCESS = 'ADD_BUISNESS_UNIT_SUCCESS'
export const ADD_BUISNESS_UNIT_FAIL = 'ADD_BUISNESS_UNIT_FAIL'

export const EDIT_BUISNESS_UNIT_START = 'EDIT_BUISNESS_UNIT_START'
export const EDIT_BUISNESS_UNIT_SUCCESS = 'EDIT_BUISNESS_UNIT_SUCCESS'
export const EDIT_BUISNESS_UNIT_FAIL = 'EDIT_BUISNESS_UNIT_FAIL'

export const BUISNESS_UNIT_BY_ID_START = 'BUISNESS_UNIT_BY_ID_START'
export const BUISNESS_UNIT_BY_ID_SUCCESS = 'BUISNESS_UNIT_BY_ID_SUCCESS'
export const BUISNESS_UNIT_BY_ID_FAIL = 'BUISNESS_UNIT_BY_ID_FAIL'

//VENDOR

export const GET_VENDOR_START = 'GET_VENDOR_START'
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS'
export const GET_VENDOR_FAIL = 'GET_VENDOR_FAIL'

export const ADD_VENDOR_START = 'ADD_VENDOR_START'
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS'
export const ADD_VENDOR_FAIL = 'ADD_VENDOR_FAIL'

export const EDIT_VENDOR_START = 'EDIT_VENDOR_START'
export const EDIT_VENDOR_SUCCESS = 'EDIT_VENDOR_SUCCESS'
export const EDIT_VENDOR_FAIL = 'EDIT_VENDOR_FAIL'

export const VENDOR_BY_ID_START = 'VENDOR_BY_ID_START'
export const VENDOR_BY_ID_SUCCESS = 'VENDOR_BY_ID_SUCCESS'
export const VENDOR_BY_ID_FAIL = 'VENDOR_BY_ID_FAIL'

export const GET_COST_CENTER_START = 'GET_COST_CENTER_START'
export const GET_COST_CENTER_SUCCESS = 'GET_COST_CENTER_SUCCESS'
export const GET_COST_CENTER_FAIL = 'GET_COST_CENTER_FAIL'

export const EDIT_COST_CENTER_START = 'EDIT_COST_CENTER_START'
export const EDIT_COST_CENTER_SUCCESS = 'EDIT_COST_CENTER_SUCCESS'
export const EDIT_COST_CENTER_FAIL = 'EDIT_COST_CENTER_FAIL'

export const GET_COST_CENTER_BY_ID_START = 'GET_COST_CENTER_BY_ID_START'
export const GET_COST_CENTER_BY_ID_SUCCESS = 'GET_COST_CENTER_BY_ID_SUCCESS'
export const GET_COST_CENTER_BY_ID_FAIL = 'GET_COST_CENTER_BY_ID_FAIL'

export const ADD_COST_CENTER_START = 'ADD_COST_CENTER_START'
export const ADD_COST_CENTER_SUCCESS = 'ADD_COST_CENTER_SUCCESS'
export const ADD_COST_CENTER_FAIL = 'ADD_COST_CENTER_FAIL'

export const GET_SAMPLES_START = 'GET_SAMPLES_START'
export const GET_SAMPLES_SUCCESS = 'GET_SAMPLES_SUCCESS'
export const GET_SAMPLES_FAIL = 'GET_SAMPLES_FAIL'

export const EDIT_SAMPLES_START = 'EDIT_SAMPLES_START'
export const EDIT_SAMPLES_SUCCESS = 'EDIT_SAMPLES_SUCCESS'
export const EDIT_SAMPLES_FAIL = 'EDIT_SAMPLES_FAIL'

export const GET_SAMPLES_BY_ID_START = 'GET_SAMPLES_BY_ID_START'
export const GET_SAMPLES_BY_ID_SUCCESS = 'GET_SAMPLES_BY_ID_SUCCESS'
export const GET_SAMPLES_BY_ID_FAIL = 'GET_SAMPLES_BY_ID_FAIL'

export const ADD_SAMPLES_START = 'ADD_SAMPLES_START'
export const ADD_SAMPLES_SUCCESS = 'ADD_SAMPLES_SUCCESS'
export const ADD_SAMPLES_FAIL = 'ADD_SAMPLES_FAIL'
