export const ADD_HSN_START_ACTION = 'ADD_HSN_START_ACTION'
export const ADD_HSN_SUCCESS_ACTION = 'ADD_HSN_SUCCESS_ACTION'
export const ADD_HSN_FAIL_ACTION = 'ADD_HSN_FAIL_ACTION'

export const ADD_BOX_WEIGHT_START_ACTION = 'ADD_BOX_WEIGHT_START_ACTION'
export const ADD_BOX_WEIGHT_SUCCESS_ACTION = 'ADD_BOX_WEIGHT_SUCCESS_ACTION'
export const ADD_BOX_WEIGHT_FAIL_ACTION = 'ADD_BOX_WEIGHT_FAIL_ACTION'
