export const UNACKNOWLEDGE_LIST_START = 'UNACKNOWLEDGE_LIST_START'
export const UNACKNOWLEDGE_LIST_SUCCESS = 'UNACKNOWLEDGE_LIST_SUCCESS'
export const UNACKNOWLEDGE_LIST_FAIL = 'UNACKNOWLEDGE_LIST_FAIL'

export const UNACKNOWLEDGE_LIST_RESET = 'UNACKNOWLEDGE_LIST_RESET'

export const REJECT_ACKNOWLEDGE_START = 'REJECT_ACKNOWLEDGE_START'
export const REJECT_ACKNOWLEDGE_SUCCESS = 'REJECT_ACKNOWLEDGE_SUCCESS'
export const REJECT_ACKNOWLEDGE_FAIL = 'REJECT_ACKNOWLEDGE_FAIL'

export const APPROVE_ACKNOWLEDGE_START = 'APPROVE_ACKNOWLEDGE_START'
export const APPROVE_ACKNOWLEDGE_SUCCESS = 'APPROVE_ACKNOWLEDGE_SUCCESS'
export const APPROVE_ACKNOWLEDGE_FAIL = 'APPROVE_ACKNOWLEDGE_FAIL'

export const GRN_START = 'GRN_START'
export const GRN_SUCCESS = 'GRN_SUCCESS'
export const GRN_FAIL = 'GRN_FAIL'
