export const LOGIN_START_ACTION = 'LOGIN_START_ACTION'
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION'
export const LOGIN_FAIL_ACTION = 'LOGIN_FAIL_ACTION'

export const LOAD_USER_PROFILE_START_ACTION = 'LOAD_USER_PROFILE_START_ACTION'
export const LOAD_USER_PROFILE_SUCCESS_ACTION = 'LOAD_USER_PROFILE_SUCCESS_ACTION'
export const LOAD_USER_PROFILE_FAIL_ACTION = 'LOAD_USER_PROFILE_FAIL_ACTION'

export const LOGOUT_START_ACTION = 'LOGOUT_START_ACTION'
export const LOGOUT_SUCCESS_ACTION = 'LOGOUT_SUCCESS_ACTION'
export const LOGOUT_FAIL_ACTION = 'LOGOUT_FAIL_ACTION'

