export const GET_BATCH_RECONCILIATION_START = 'GET_BATCH_RECONCILIATION_START'
export const GET_BATCH_RECONCILIATION_SUCCESS = 'GET_BATCH_RECONCILIATION_SUCCESS'
export const GET_BATCH_RECONCILIATION_FAIL = 'GET_BATCH_RECONCILIATION_FAIL'

export const GET_VIRTUAL_RECONCILIATION_REPORT_START = 'GET_VIRTUAL_RECONCILIATION_REPORT_START'
export const GET_VIRTUAL_RECONCILIATION_REPORT_SUCCESS = 'GET_VIRTUAL_RECONCILIATION_REPORT_SUCCESS'
export const GET_VIRTUAL_RECONCILIATION_REPORT_FAIL = 'GET_VIRTUAL_RECONCILIATION_REPORT_FAIL'

export const GET_SHIP_ROCKET_REPORT_START = 'GET_SHIP_ROCKET_REPORT_START'
export const GET_SHIP_ROCKET_REPORT_SUCCESS = 'GET_SHIP_ROCKET_REPORT_SUCCESS'
export const GET_SHIP_ROCKET_REPORT_FAIL = 'GET_SHIP_ROCKET_REPORT_FAIL'


export const OVER_SAMPLING_MAIL_START = 'OVER_SAMPLING_MAIL_START'
export const OVER_SAMPLING_MAIL_SUCCESS = 'OVER_SAMPLING_MAIL_SUCCESS'
export const OVER_SAMPLING_MAIL_FAIL = 'OVER_SAMPLING_MAIL_FAIL'
