export const GET_DESTRUCTION_REPORT_START = 'GET_DESTRUCTION_REPORT_START'
export const GET_DESTRUCTION_REPORT_SUCCESS = 'GET_DESTRUCTION_REPORT_SUCCESS'
export const GET_DESTRUCTION_REPORT_FAIL = 'GET_DESTRUCTION_REPORT_FAIL'
