export const GET_DEVIATION_REPORT_START = 'GET_DEVIATION_REPORT_START'
export const GET_DEVIATION_REPORT_SUCCESS = 'GET_DEVIATION_REPORT_SUCCESS'
export const GET_DEVIATION_REPORT_FAIL = 'GET_DEVIATION_REPORT_FAIL'
