export const GET_DISPATCHES_REPORT_START = 'GET_DISPATCHES_REPORT_START'
export const GET_DISPATCHES_REPORT_SUCCESS = 'GET_DISPATCHES_REPORT_SUCCESS'
export const GET_DISPATCHES_REPORT_FAIL = 'GET_DISPATCHES_REPORT_FAIL'
