export const GET_PURCHASE_REPORT_START = 'GET_PURCHASE_REPORT_START'
export const GET_PURCHASE_REPORT_SUCCESS = 'GET_PURCHASE_REPORT_SUCCESS'
export const GET_PURCHASE_REPORT_FAIL = 'GET_PURCHASE_REPORT_FAIL'
