export const GET_RECIPIENT_REPORT_START = 'GET_RECIPIENT_REPORT_START'
export const GET_RECIPIENT_REPORT_SUCCESS = 'GET_RECIPIENT_REPORT_SUCCESS'
export const GET_RECIPIENT_REPORT_FAIL = 'GET_RECIPIENT_REPORT_FAIL'
