export const GET_INVENTORY_REPORT_START = 'GET_INVENTORY_REPORT_START'
export const GET_INVENTORY_REPORT_SUCCESS = 'GET_INVENTORY_REPORT_SUCCESS'
export const GET_INVENTORY_REPORT_FAIL = 'GET_INVENTORY_REPORT_FAIL'
