//MONTHLY APPROVAL
export const GET_MONTHLY_APPROVAL_START = 'GET_MONTHLY_APPROVAL_START'
export const GET_MONTHLY_APPROVAL_SUCCESS = 'GET_MONTHLY_APPROVAL_SUCCESS'
export const GET_MONTHLY_APPROVAL_FAIL = 'GET_MONTHLY_APPROVAL_FAIL'
