import {MONTHLY_COMMON_TEAM_API} from "../../../api/apiConstants";

export const ALLOCATION_PAGE_RESET = 'ALLOCATION_PAGE_RESET'
export const MONTHLY_ALLOCATION_START = 'MONTHLY_ALLOCATION_START'
export const MONTHLY_ALLOCATION_SUCCESS = 'MONTHLY_ALLOCATION_SUCCESS'
export const MONTHLY_ALLOCATION_FAIL = 'MONTHLY_ALLOCATION_FAIL'

export const GET_ALLOCATIONS_FOR_PLAN_START = 'GET_ALLOCATIONS_FOR_PLAN_START'
export const GET_ALLOCATIONS_FOR_PLAN_SUCCESS = 'GET_ALLOCATIONS_FOR_PLAN_SUCCESS'
export const GET_ALLOCATIONS_FOR_PLAN_FAIL = 'GET_ALLOCATIONS_FOR_PLAN_FAIL'

export const ALLOCATE_TO_TEAM = 'ALLOCATE_TO_TEAM'
export const ALLOCATE_TO_DIFFERENTIAL = 'ALLOCATE_TO_DIFFERENTIAL'
export const ALLOCATE_TO_ALL_TEAMS = 'ALLOCATE_TO_ALL_TEAMS'

export const VIRTUAL_ALLOCATE_TO_TEAM = 'VIRTUAL_ALLOCATE_TO_TEAM'
export const VIRTUAL_ALLOCATE_TO_DIFFERENTIAL = 'VIRTUAL_ALLOCATE_TO_DIFFERENTIAL'
export const SPECIAL_ALLOCATE_TO_DIFFERENTIAL = 'SPECIAL_ALLOCATE_TO_DIFFERENTIAL'


//
export const RECIPIENTS_TO_ALLOCATE_LIST_START = 'RECIPIENTS_TO_ALLOCATE_LIST_START'
export const RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS = 'RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS'
export const RECIPIENTS_TO_ALLOCATE_LIST_FAIL = 'RECIPIENTS_TO_ALLOCATE_LIST_FAIL'
export const RECIPIENTS_TO_ALLOCATE_LIST_RESET = 'RECIPIENTS_TO_ALLOCATE_LIST_RESET'


export const MONTHLY_COMMON_TEAM_START = 'MONTHLY_COMMON_TEAM_START'
export const MONTHLY_COMMON_TEAM_SUCCESS = 'MONTHLY_COMMON_TEAM_SUCCESS'
export const MONTHLY_COMMON_TEAM_FAIL = 'MONTHLY_COMMON_TEAM_FAIL'

export const MONTHLY_DIFFERENTIAL_TEAM_START = 'MONTHLY_DIFFERENTIAL_TEAM_START'
export const MONTHLY_DIFFERENTIAL_TEAM_SUCCESS = 'MONTHLY_DIFFERENTIAL_TEAM_SUCCESS'
export const MONTHLY_DIFFERENTIAL_TEAM_FAIL = 'MONTHLY_DIFFERENTIAL_TEAM_FAIL'

export const MONTHLY_COMMON_ALLOCATION_SAVE_START = 'MONTHLY_COMMON_ALLOCATION_SAVE_START'
export const MONTHLY_COMMON_ALLOCATION_SAVE_SUCCESS = 'MONTHLY_COMMON_ALLOCATION_SAVE_SUCCESS'
export const MONTHLY_COMMON_ALLOCATION_SAVE_FAIL = 'MONTHLY_COMMON_ALLOCATION_SAVE_FAIL'

export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_START = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_START'
export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS'
export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_FAIL = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_FAIL'

export const VIRTUAL_COMMON_ALLOCATION_SAVE_START = 'VIRTUAL_COMMON_ALLOCATION_SAVE_START'
export const VIRTUAL_COMMON_ALLOCATION_SAVE_SUCCESS = 'VIRTUAL_COMMON_ALLOCATION_SAVE_SUCCESS'
export const VIRTUAL_COMMON_ALLOCATION_SAVE_FAIL = 'VIRTUAL_COMMON_ALLOCATION_SAVE_FAIL'

export const GET_DOWNLOAD_ALLOCATION_START = 'GET_DOWNLOAD_ALLOCATION_START'
export const GET_DOWNLOAD_ALLOCATION_SUCCESS = 'GET_DOWNLOAD_ALLOCATION_SUCCESS'
export const GET_DOWNLOAD_ALLOCATION_FAIL = 'GET_DOWNLOAD_ALLOCATION_FAIL'

export const GET_BLOCKED_RECIPIENT_START = 'GET_BLOCKED_RECIPIENT_START'
export const GET_BLOCKED_RECIPIENT_SUCCESS = 'GET_BLOCKED_RECIPIENT_SUCCESS'
export const GET_BLOCKED_RECIPIENT_FAIL = 'GET_BLOCKED_RECIPIENT_FAIL'

export const GET_ACTIVE_USERS_START = 'GET_ACTIVE_USERS_START'
export const GET_ACTIVE_USERS_SUCCESS = 'GET_ACTIVE_USERS_SUCCESS'
export const GET_ACTIVE_USERS_FAIL = 'GET_ACTIVE_USERS_FAIL'

export const VIRTUAL_ALLOCATION_START = 'VIRTUAL_ALLOCATION_START'
export const VIRTUAL_ALLOCATION_SUCCESS = 'VIRTUAL_ALLOCATION_SUCCESS'
export const VIRTUAL_ALLOCATION_FAIL = 'VIRTUAL_ALLOCATION_FAIL'

export const SEARCH_SPECIAL_PLAN_START = 'SEARCH_SPECIAL_PLAN_START'
export const SEARCH_SPECIAL_PLAN_SUCCESS = 'SEARCH_SPECIAL_PLAN_SUCCESS'
export const SEARCH_SPECIAL_PLAN_FAIL = 'SEARCH_SPECIAL_PLAN_FAIL'

export const VIRTUAL_COMMON_TEAM_START = 'VIRTUAL_COMMON_TEAM_START'
export const VIRTUAL_COMMON_TEAM_SUCCESS = 'VIRTUAL_COMMON_TEAM_SUCCESS'
export const VIRTUAL_COMMON_TEAM_FAIL = 'VIRTUAL_COMMON_TEAM_FAIL'

export const GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_START = 'GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_START'
export const GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_SUCCESS = 'GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_SUCCESS'
export const GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_FAIL = 'GET_VIRTUAL_ALLOCATIONS_FOR_PLAN_FAIL'

export const VIRTUAL_DIFFERENTIAL_TEAM_START = 'VIRTUAL_DIFFERENTIAL_TEAM_START'
export const VIRTUAL_DIFFERENTIAL_TEAM_SUCCESS = 'VIRTUAL_DIFFERENTIAL_TEAM_SUCCESS'
export const VIRTUAL_DIFFERENTIAL_TEAM_FAIL = 'VIRTUAL_DIFFERENTIAL_TEAM_FAIL'

export const VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_START = 'VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_START'
export const VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS = 'VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS'
export const VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_FAIL = 'VIRTUAL_DIFFERENTIAL_ALLOCATION_SAVE_FAIL'

export const SUBMIT_MONTHLY_ALLOCATION_START = 'SUBMIT_MONTHLY_ALLOCATION_START'
export const SUBMIT_MONTHLY_ALLOCATION_SUCCESS = 'SUBMIT_MONTHLY_ALLOCATION_SUCCESS'
export const SUBMIT_MONTHLY_ALLOCATION_FAIL = 'SUBMIT_MONTHLY_ALLOCATION_FAIL'

export const SUBMIT_VIRTUAL_ALLOCATION_START = 'SUBMIT_VIRTUAL_ALLOCATION_START'
export const SUBMIT_VIRTUAL_ALLOCATION_SUCCESS = 'SUBMIT_VIRTUAL_ALLOCATION_SUCCESS'
export const SUBMIT_VIRTUAL_ALLOCATION_FAIL = 'SUBMIT_VIRTUAL_ALLOCATION_FAIL'

export const SUBMIT_SPECIAL_ALLOCATION_START = 'SUBMIT_SPECIAL_ALLOCATION_START'
export const SUBMIT_SPECIAL_ALLOCATION_SUCCESS = 'SUBMIT_SPECIAL_ALLOCATION_SUCCESS'
export const SUBMIT_SPECIAL_ALLOCATION_FAIL = 'SUBMIT_SPECIAL_ALLOCATION_FAIL'

export const GET_ALLOCATION_STATUS_DROPDOWN_START = 'GET_ALLOCATION_STATUS_DROPDOWN_START'
export const GET_ALLOCATION_STATUS_DROPDOWN_SUCCESS = 'GET_ALLOCATION_STATUS_DROPDOWN_SUCCESS'
export const GET_ALLOCATION_STATUS_DROPDOWN_FAIL = 'GET_ALLOCATION_STATUS_DROPDOWN_FAIL'

export const GET_MULTIPLE_ALLOCATION_DOWNLOAD_START = 'GET_MULTIPLE_ALLOCATION_DOWNLOAD_START'
export const GET_MULTIPLE_ALLOCATION_DOWNLOAD_SUCCESS = 'GET_MULTIPLE_ALLOCATION_DOWNLOAD_SUCCESS'
export const GET_MULTIPLE_ALLOCATION_DOWNLOAD_FAIL = 'GET_MULTIPLE_ALLOCATION_DOWNLOAD_FAIL'

export const EDIT_SPECIAL_PLAN_START = 'EDIT_SPECIAL_PLAN_START'
export const EDIT_SPECIAL_PLAN_SUCCESS = 'EDIT_SPECIAL_PLAN_SUCCESS'
export const EDIT_SPECIAL_PLAN_FAIL = 'EDIT_SPECIAL_PLAN_FAIL'

export const SPECIAL_ALLOCATION_START = 'SPECIAL_ALLOCATION_START'
export const SPECIAL_ALLOCATION_SUCCESS = 'SPECIAL_ALLOCATION_SUCCESS'
export const SPECIAL_ALLOCATION_FAIL = 'SPECIAL_ALLOCATION_FAIL'

export const GET_SPECIAL_ALLOCATIONS_FOR_PLAN_START = 'GET_SPECIAL_ALLOCATIONS_FOR_PLAN_START'
export const GET_SPECIAL_ALLOCATIONS_FOR_PLAN_SUCCESS = 'GET_SPECIAL_ALLOCATIONS_FOR_PLAN_SUCCESS'
export const GET_SPECIAL_ALLOCATIONS_FOR_PLAN_FAIL = 'GET_SPECIAL_ALLOCATIONS_FOR_PLAN_FAIL'

export const SPECIAL_DIFFERENTIAL_TEAM_START = 'SPECIAL_DIFFERENTIAL_TEAM_START'
export const SPECIAL_DIFFERENTIAL_TEAM_SUCCESS = 'SPECIAL_DIFFERENTIAL_TEAM_SUCCESS'
export const SPECIAL_DIFFERENTIAL_TEAM_FAIL = 'SPECIAL_DIFFERENTIAL_TEAM_FAIL'

export const SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_START = 'SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_START'
export const SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS = 'SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS'
export const SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_FAIL = 'SPECIAL_DIFFERENTIAL_ALLOCATION_SAVE_FAIL'

export const DELETE_SPECIAL_ALLOCATION_START = 'DELETE_SPECIAL_ALLOCATION_START'
export const DELETE_SPECIAL_ALLOCATION_SUCCESS = 'DELETE_SPECIAL_ALLOCATION_SUCCESS'
export const DELETE_SPECIAL_ALLOCATION_FAIL = 'DELETE_SPECIAL_ALLOCATION_FAIL'

export const MULTIPLE_ALLOCATION_UPLOAD_START = 'MULTIPLE_ALLOCATION_UPLOAD_START'
export const MULTIPLE_ALLOCATION_UPLOAD_SUCCESS = 'MULTIPLE_ALLOCATION_UPLOAD_SUCCESS'
export const MULTIPLE_ALLOCATION_UPLOAD_FAIL = 'MULTIPLE_ALLOCATION_UPLOAD_FAIL'
