import {MONTHLY_COMMON_TEAM_API} from "../../../api/apiConstants";

export const ALLOCATION_PAGE_RESET = 'ALLOCATION_PAGE_RESET'
export const MONTHLY_ALLOCATION_START = 'MONTHLY_ALLOCATION_START'
export const MONTHLY_ALLOCATION_SUCCESS = 'MONTHLY_ALLOCATION_SUCCESS'
export const MONTHLY_ALLOCATION_FAIL = 'MONTHLY_ALLOCATION_FAIL'

export const GET_ALLOCATIONS_FOR_PLAN_START = 'GET_ALLOCATIONS_FOR_PLAN_START'
export const GET_ALLOCATIONS_FOR_PLAN_SUCCESS = 'GET_ALLOCATIONS_FOR_PLAN_SUCCESS'
export const GET_ALLOCATIONS_FOR_PLAN_FAIL = 'GET_ALLOCATIONS_FOR_PLAN_FAIL'

export const ALLOCATE_TO_TEAM = 'ALLOCATE_TO_TEAM'
export const ALLOCATE_TO_DIFFERENTIAL = 'ALLOCATE_TO_DIFFERENTIAL'
export const ALLOCATE_TO_ALL_TEAMS = 'ALLOCATE_TO_ALL_TEAMS'

//
export const RECIPIENTS_TO_ALLOCATE_LIST_START = 'RECIPIENTS_TO_ALLOCATE_LIST_START'
export const RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS = 'RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS'
export const RECIPIENTS_TO_ALLOCATE_LIST_FAIL = 'RECIPIENTS_TO_ALLOCATE_LIST_FAIL'
export const RECIPIENTS_TO_ALLOCATE_LIST_RESET = 'RECIPIENTS_TO_ALLOCATE_LIST_RESET'


export const MONTHLY_COMMON_TEAM_START = 'MONTHLY_COMMON_TEAM_START'
export const MONTHLY_COMMON_TEAM_SUCCESS = 'MONTHLY_COMMON_TEAM_SUCCESS'
export const MONTHLY_COMMON_TEAM_FAIL = 'MONTHLY_COMMON_TEAM_FAIL'

export const MONTHLY_DIFFERENTIAL_TEAM_START = 'MONTHLY_DIFFERENTIAL_TEAM_START'
export const MONTHLY_DIFFERENTIAL_TEAM_SUCCESS = 'MONTHLY_DIFFERENTIAL_TEAM_SUCCESS'
export const MONTHLY_DIFFERENTIAL_TEAM_FAIL = 'MONTHLY_DIFFERENTIAL_TEAM_FAIL'

export const MONTHLY_COMMON_ALLOCATION_SAVE_START = 'MONTHLY_COMMON_ALLOCATION_SAVE_START'
export const MONTHLY_COMMON_ALLOCATION_SAVE_SUCCESS = 'MONTHLY_COMMON_ALLOCATION_SAVE_SUCCESS'
export const MONTHLY_COMMON_ALLOCATION_SAVE_FAIL = 'MONTHLY_COMMON_ALLOCATION_SAVE_FAIL'

export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_START = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_START'
export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_SUCCESS'
export const MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_FAIL = 'MONTHLY_DIFFERENTIAL_ALLOCATION_SAVE_FAIL'

export const VIRTUAL_COMMON_ALLOCATION_SAVE_START = 'VIRTUAL_COMMON_ALLOCATION_SAVE_START'
export const VIRTUAL_COMMON_ALLOCATION_SAVE_SUCCESS = 'VIRTUAL_COMMON_ALLOCATION_SAVE_SUCCESS'
export const VIRTUAL_COMMON_ALLOCATION_SAVE_FAIL = 'VIRTUAL_COMMON_ALLOCATION_SAVE_FAIL'
