export const ALLOCATION_PAGE_RESET = 'ALLOCATION_PAGE_RESET'
export const MONTHLY_ALLOCATION_START = 'MONTHLY_ALLOCATION_START'
export const MONTHLY_ALLOCATION_SUCCESS = 'MONTHLY_ALLOCATION_SUCCESS'
export const MONTHLY_ALLOCATION_FAIL = 'MONTHLY_ALLOCATION_FAIL'

export const GET_ALLOCATIONS_FOR_PLAN_START = 'GET_ALLOCATIONS_FOR_PLAN_START'
export const GET_ALLOCATIONS_FOR_PLAN_SUCCESS = 'GET_ALLOCATIONS_FOR_PLAN_SUCCESS'
export const GET_ALLOCATIONS_FOR_PLAN_FAIL = 'GET_ALLOCATIONS_FOR_PLAN_FAIL'

export const ALLOCATE_TO_TEAM = 'ALLOCATE_TO_TEAM'
export const ALLOCATE_TO_ALL_TEAMS = 'ALLOCATE_TO_ALL_TEAMS'

//
export const RECIPIENTS_TO_ALLOCATE_LIST_START = 'RECIPIENTS_TO_ALLOCATE_LIST_START'
export const RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS = 'RECIPIENTS_TO_ALLOCATE_LIST_SUCCESS'
export const RECIPIENTS_TO_ALLOCATE_LIST_FAIL = 'RECIPIENTS_TO_ALLOCATE_LIST_FAIL'
export const RECIPIENTS_TO_ALLOCATE_LIST_RESET = 'RECIPIENTS_TO_ALLOCATE_LIST_RESET'
