export const GET_INVOICE_UPLOAD_START = 'GET_INVOICE_UPLOAD_START'
export const GET_INVOICE_UPLOAD_SUCCESS = 'GET_INVOICE_UPLOAD_SUCCESS'
export const GET_INVOICE_UPLOAD_FAIL = 'GET_INVOICE_UPLOAD_FAIL'
