export const GET_MONTHLYDISPATCH_START = 'GET_MONTHLYDISPATCH_START'
export const GET_MONTHLYDISPATCH_SUCCESS = 'GET_MONTHLYDISPATCH_SUCCESS'
export const GET_MONTHLYDISPATCH_FAIL = 'GET_MONTHLYDISPATCH_FAIL'

export const GET_EMPLOYEEINVOICEDETAILS_START = 'GET_EMPLOYEEINVOICEDETAILS_START'
export const GET_EMPLOYEEINVOICEDETAILS_SUCCESS = 'GET_EMPLOYEEINVOICEDETAILS_SUCCESS'
export const GET_EMPLOYEEINVOICEDETAILS_FAIL = 'GET_EMPLOYEEINVOICEDETAILS_FAIL'

export const GET_PRINT_INVOICE_START = 'GET_PRINT_INVOICE_START'
export const GET_PRINT_INVOICE_SUCCESS = 'GET_PRINT_INVOICE_SUCCESS'
export const GET_PRINT_INVOICE_FAIL = 'GET_PRINT_INVOICE_FAIL'

export const GET_GENERATE_INVOICE_START = 'GET_GENERATE_INVOICE_START'
export const GET_GENERATE_INVOICE_SUCCESS = 'GET_GENERATE_INVOICE_SUCCESS'
export const GET_GENERATE_INVOICE_FAIL = 'GET_GENERATE_INVOICE_FAIL'
