export const GET_MONTHLYDISPATCH_START = 'GET_MONTHLYDISPATCH_START'
export const GET_MONTHLYDISPATCH_SUCCESS = 'GET_MONTHLYDISPATCH_SUCCESS'
export const GET_MONTHLYDISPATCH_FAIL = 'GET_MONTHLYDISPATCH_FAIL'



export const GET_EMPLOYEEINVOICEDETAILS_START = 'GET_EMPLOYEEINVOICEDETAILS_START'
export const GET_EMPLOYEEINVOICEDETAILS_SUCCESS = 'GET_EMPLOYEEINVOICEDETAILS_SUCCESS'
export const GET_EMPLOYEEINVOICEDETAILS_FAIL = 'GET_EMPLOYEEINVOICEDETAILS_FAIL'
