export const GET_SPECIALDISPATCH_START = 'GET_SPECIALDISPATCH_START'
export const GET_SPECIALDISPATCH_SUCCESS = 'GET_SPECIALDISPATCH_SUCCESS'
export const GET_SPECIALDISPATCH_FAIL = 'GET_SPECIALDISPATCH_FAIL'



export const GET_SPECIALEMPLOYEEINVOICEDETAILS_START = 'GET_SPECIALEMPLOYEEINVOICEDETAILS_START'
export const GET_SPECIALEMPLOYEEINVOICEDETAILS_SUCCESS = 'GET_SPECIALEMPLOYEEINVOICEDETAILS_SUCCESS'
export const GET_SPECIALEMPLOYEEINVOICEDETAILS_FAIL = 'GET_SPECIALEMPLOYEEINVOICEDETAILS_FAIL'
