export const GET_VIRTUAL_DISPATCH_START = 'GET_VIRTUAL_DISPATCH_START'
export const GET_VIRTUAL_DISPATCH_SUCCESS = 'GET_VIRTUAL_DISPATCH_SUCCESS'
export const GET_VIRTUAL_DISPATCH_FAIL = 'GET_VIRTUAL_DISPATCH_FAIL'
//
export const GET_VIRTUAL_DISPATCH_DETAILS_START = 'GET_VIRTUAL_DISPATCH_DETAILS_START'
export const GET_VIRTUAL_DISPATCH_DETAILS_SUCCESS = 'GET_VIRTUAL_DISPATCH_DETAILS_SUCCESS'
export const GET_VIRTUAL_DISPATCH_DETAILS_FAIL = 'GET_VIRTUAL_DISPATCH_DETAILS_FAIL'


export const GET_GEN_VIRTUAL_INVOICE_START = 'GET_GEN_VIRTUAL_INVOICE_START'
export const GET_GEN_VIRTUAL_INVOICE_SUCCESS = 'GET_GEN_VIRTUAL_INVOICE_SUCCESS'
export const GET_GEN_VIRTUAL_INVOICE_FAIL = 'GET_GEN_VIRTUAL_INVOICE_FAIL'
