export const GET_VIRTUAL_DISPATCH_START = 'GET_VIRTUAL_DISPATCH_START'
export const GET_VIRTUAL_DISPATCH_SUCCESS = 'GET_VIRTUAL_DISPATCH_SUCCESS'
export const GET_VIRTUAL_DISPATCH_FAIL = 'GET_VIRTUAL_DISPATCH_FAIL'
//
export const GET_VIRTUAL_DISPATCH_DETAILS_START = 'GET_VIRTUAL_DISPATCH_DETAILS_START'
export const GET_VIRTUAL_DISPATCH_DETAILS_SUCCESS = 'GET_VIRTUAL_DISPATCH_DETAILS_SUCCESS'
export const GET_VIRTUAL_DISPATCH_DETAILS_FAIL = 'GET_VIRTUAL_DISPATCH_DETAILS_FAIL'
